languageCode:           "en"
title:                  "Snowdrop"
baseURL:                "https://ccswbs.github.io/snowdrop"

canonifyurls:             true
relativeurls:             true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/1.1/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/1.1/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/1.1/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Based on the most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/1.1/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/1.1/assets/brand/bootstrap-social-logo.png

  current_version:      "1.1.0"
  current_ruby_version: "1.1.0"
  docs_version:         "1.1"
  rfs_version:          "v9.0.6"
  github_org:           "https://github.com/twbs"
  repo:                 "https://github.com/ccswbs/snowdrop"
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://fontawesome.com/"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v5.2.3.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v5.2.3/bootstrap-5.2.3-dist.zip"
    dist_examples:      "https://github.com/twbs/bootstrap/releases/download/v5.2.3/bootstrap-5.2.3-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    # css:              "https://cdn.jsdelivr.net/npm/@uoguelph/snowdrop@1.0.2/dist/css/snowdrop.min.css"
    # css_hash:         "sha384-rFNEnbZryCwg3RvqQAiYLywmAf/o/s1WNbvYYomaC8/uceo0KXquqRnSxK4C8cqj"
    # js:               "https://cdn.jsdelivr.net/npm/@uoguelph/snowdrop@1.0.2/dist/js/snowdrop.min.js"
    # js_hash:          "sha384-CqL5VoBM60od+hffPxH5uST8TXRyY8iGxasX6TgKsYwZF5aiZpf1unZLH7xqyd9x"
    # js_bundle:        "https://cdn.jsdelivr.net/npm/@uoguelph/snowdrop@1.0.2/dist/js/snowdrop.bundle.min.js"
    # js_bundle_hash:   "sha384-/reCR9/hRvGdYiAeyMI3082VPb1FQ+R46r4M4Jw0iWNKJeXXmy/xj0dbKwgjtMZG"
    css:              "https://ccswbs.github.io/snowdrop/1.1/docs/1.1/dist/css/snowdrop.min.css"
    css_hash:         "sha384-7TcRMaCaMU4lKmF9l1GAX/9NWlp5nBDp68a7mpbqR4KN9PDjzCOqT1uSE7RzEHeE"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@1.0.2/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q"
    js:               "https://ccswbs.github.io/snowdrop/1.1/docs/1.1/dist/js/snowdrop.min.js"
    js_hash:          "sha384-4lGV3bx3BCECLAh6k3Srdx/ItkFrgm2ufVZmX4F1RBRM7EIfkcelHqS9ExKrF5lD"
    js_bundle:        "https://ccswbs.github.io/snowdrop/1.1/docs/1.1/dist/js/snowdrop.bundle.min.js"
    js_bundle_hash:   "sha384-M5WxJd4OqISS9FyCIzoKmeyLTS4N4p1iV/BuDaRF8LnuWOUslA8z+XyG5micDLr9"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:      "sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"

  anchors:
    min: 2
    max: 5
